name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  work-with-docker-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build docker
      run: docker build -t lab3-docker .

    - name: Run docker
      run: docker run --name docker_for_lab lab3-docker

    - name: Copy file from docker
      run: docker cp docker_for_lab:/result.txt $GITHUB_WORKSPACE

    - name: Login on DockerHub
      run: docker login -u ${{ secrets.USER }} -p ${{ secrets.PASSWORD }}

    - name: Push image on DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.USER }}/lab3:latest